// =============================================================================
// JURI-X — Forensic Intelligence Platform
// Comprehensive Sample Data: "Operation Shadow Access"
// Insider threat investigation — John Doe suspected of stealing confidential data
// =============================================================================

import type {
  Evidence,
  CaseInfo,
  TimelineEvent,
  RewindEvent,
  CorrelationGraph,
  SuspiciousFinding,
  KeywordResult,
  GeoIPResult,
  ActivityHeatmap,
  CustodyEntry,
  AnalysisResult,
  ForensicReport,
  ActionCategory,
  SeverityLevel,
} from './types';

// =============================================================================
// CASE INFO
// =============================================================================

export function getSampleCaseInfo(): CaseInfo {
  return {
    id: 'case-001',
    name: 'Operation Shadow Access',
    description:
      'Insider threat investigation. Employee John Doe (jdoe@acmecorp.com) is suspected of stealing confidential project data, customer databases, and proprietary source code. The unauthorized access occurred between March 15–17, 2026 across multiple workstations and involved USB exfiltration, Tor network usage, and cloud storage uploads.',
    createdAt: '2026-03-18T08:00:00.000Z',
    status: 'active',
    evidenceIds: [
      'evid-001',
      'evid-002',
      'evid-003',
      'evid-004',
      'evid-005',
      'evid-006',
      'evid-007',
    ],
    analyst: 'Sarah Chen, CFCE / CCE',
  };
}

// =============================================================================
// EVIDENCE
// =============================================================================

export function getSampleEvidence(): Evidence[] {
  return [
    {
      id: 'evid-001',
      caseId: 'case-001',
      name: 'WS-JDOE-01_disk_image.E01',
      type: 'disk_image',
      path: '/evidence/case-001/WS-JDOE-01_disk_image.E01',
      size: 473_248_293_888,
      hash: 'sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
      status: 'analyzed',
      uploadedAt: '2026-03-18T09:15:00.000Z',
      analyzedAt: '2026-03-18T14:30:00.000Z',
      metadata: {
        acquisitionTool: 'FTK Imager 4.7.3',
        blockSize: 65536,
        imageFormat: 'E01',
        verified: true,
      },
    },
    {
      id: 'evid-002',
      caseId: 'case-001',
      name: 'NTUSER.DAT_registry_hive',
      type: 'registry_hive',
      path: '/evidence/case-001/WS-JDOE-01/NTUSER.DAT',
      size: 26_214_400,
      hash: 'sha256:b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3',
      status: 'analyzed',
      uploadedAt: '2026-03-18T09:20:00.000Z',
      analyzedAt: '2026-03-18T15:00:00.000Z',
      metadata: { lastWritten: '2026-03-17T16:45:00.000Z' },
    },
    {
      id: 'evid-003',
      caseId: 'case-001',
      name: 'Chrome_history_browse.db',
      type: 'browser_data',
      path: '/evidence/case-001/WS-JDOE-01/browsers/chrome/History',
      size: 12_582_912,
      hash: 'sha256:c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4',
      status: 'analyzed',
      uploadedAt: '2026-03-18T09:25:00.000Z',
      analyzedAt: '2026-03-18T15:30:00.000Z',
      metadata: { browser: 'Google Chrome 122.0.6261.112', profile: 'Default' },
    },
    {
      id: 'evid-004',
      caseId: 'case-001',
      name: 'Windows_Event_Logs.evtx',
      type: 'log_file',
      path: '/evidence/case-001/WS-JDOE-01/evtx/Security.evtx',
      size: 209_715_200,
      hash: 'sha256:d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5',
      status: 'analyzed',
      uploadedAt: '2026-03-18T09:30:00.000Z',
      analyzedAt: '2026-03-18T16:00:00.000Z',
      metadata: { eventCount: 287_412, dateRange: '2026-03-01 to 2026-03-17' },
    },
    {
      id: 'evid-005',
      caseId: 'case-001',
      name: 'Prefetch_files_collection',
      type: 'prefetch',
      path: '/evidence/case-001/WS-JDOE-01/Prefetch/',
      size: 5_242_880,
      hash: 'sha256:e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6',
      status: 'analyzed',
      uploadedAt: '2026-03-18T09:35:00.000Z',
      analyzedAt: '2026-03-18T16:30:00.000Z',
      metadata: { prefetchCount: 342, suspiciousExecutables: 7 },
    },
    {
      id: 'evid-006',
      caseId: 'case-001',
      name: 'USB_forensic_image_SANSA.raw',
      type: 'disk_image',
      path: '/evidence/case-001/USB_SANSA_64GB.raw',
      size: 64_213_033_472,
      hash: 'sha256:f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7',
      status: 'analyzed',
      uploadedAt: '2026-03-18T10:00:00.000Z',
      analyzedAt: '2026-03-18T17:00:00.000Z',
      metadata: {
        deviceName: 'SANSA 64GB',
        serialNumber: 'USB-SN-789012',
        fileSystem: 'exFAT',
        recoveredFiles: 47,
      },
    },
    {
      id: 'evid-007',
      caseId: 'case-001',
      name: 'Network_capture_Mar15-17.pcap',
      type: 'network_capture',
      path: '/evidence/case-001/network/WS-JDOE-01_Mar15-17.pcap',
      size: 4_194_304_000,
      hash: 'sha256:a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8',
      status: 'analyzed',
      uploadedAt: '2026-03-18T10:15:00.000Z',
      analyzedAt: '2026-03-18T18:00:00.000Z',
      metadata: {
        packetCount: 18_432_891,
        uniqueIPs: 142,
        torConnections: 23,
        totalDataTransferred: '4.7 GB',
      },
    },
  ];
}

// =============================================================================
// TIMELINE EVENTS (45 events)
// =============================================================================

const timelineEvents: TimelineEvent[] = [
  // --- Day 1: March 15, 2026 ---
  {
    id: 'evt-001',
    timestamp: '2026-03-15T08:12:33.000Z',
    action: 'login_attempt',
    entity: 'JDOE\\jdoe',
    description: 'Interactive logon at workstation WS-JDOE-01 from local session.',
    source: 'Windows Security Event Log (4624)',
    confidence: 0.98,
    severity: 'benign',
    metadata: { logonType: 2, authPackage: 'Negotiate', workstation: 'WS-JDOE-01' },
    relatedEvents: [],
  },
  {
    id: 'evt-002',
    timestamp: '2026-03-15T08:14:02.000Z',
    action: 'process_created',
    entity: 'explorer.exe',
    description: 'Windows Explorer shell process started as part of user session initialization.',
    source: 'Windows Security Event Log (4688)',
    confidence: 0.97,
    severity: 'benign',
    metadata: { parentPID: 1024, pid: 4832, user: 'ACMECORP\\jdoe' },
    relatedEvents: ['evt-001'],
  },
  {
    id: 'evt-003',
    timestamp: '2026-03-15T08:22:10.000Z',
    action: 'browser_opened',
    entity: 'chrome.exe',
    description: 'Google Chrome launched with profile "Default".',
    source: 'Prefetch / Amcache',
    confidence: 0.95,
    severity: 'benign',
    metadata: { pid: 6128, version: '122.0.6261.112' },
    relatedEvents: [],
  },
  {
    id: 'evt-004',
    timestamp: '2026-03-15T08:30:45.000Z',
    action: 'file_opened',
    entity: 'confidential_project_proposal.pdf',
    description: 'User opened confidential project proposal document stored on network share \\\\FILESERVER\\Projects\\.',
    source: 'Windows Jump Lists / Shellbags',
    confidence: 0.93,
    severity: 'benign',
    metadata: {
      filePath: '\\\\FILESERVER\\Projects\\confidential_project_proposal.pdf',
      fileSize: '2.4 MB',
      accessCount: 3,
    },
    relatedEvents: [],
  },
  {
    id: 'evt-005',
    timestamp: '2026-03-15T08:42:18.000Z',
    action: 'file_opened',
    entity: 'employee_salary_database.xlsx',
    description: 'User opened employee salary database spreadsheet from HR shared folder.',
    source: 'Recent Files / Jump Lists',
    confidence: 0.92,
    severity: 'suspicious',
    metadata: {
      filePath: '\\\\FILESERVER\\HR\\employee_salary_database.xlsx',
      fileSize: '5.1 MB',
    },
    relatedEvents: ['evt-004'],
  },
  {
    id: 'evt-006',
    timestamp: '2026-03-15T08:45:03.000Z',
    action: 'usb_connected',
    entity: 'SANSA 64GB (USB-SN-789012)',
    description: 'USB mass storage device "SANSA 64GB" connected via USB 3.0 port.',
    source: 'Windows Event Log (2003/10016) / USBSTOR registry',
    confidence: 0.99,
    severity: 'suspicious',
    metadata: {
      deviceID: 'USBSTOR\\Disk&Ven_SANSADisk&Prod_64GB&Rev_1.00\\7890123456789012',
      serialNumber: 'USB-SN-789012',
      driveLetter: 'E:\\',
      capacity: '64 GB',
      fileSystem: 'exFAT',
    },
    relatedEvents: [],
  },
  {
    id: 'evt-007',
    timestamp: '2026-03-15T08:52:11.000Z',
    action: 'file_created',
    entity: 'E:\\staging\\confidential_project_proposal.pdf',
    description: 'Confidential project proposal copied to USB staging directory.',
    source: 'USN Journal / MFT',
    confidence: 0.96,
    severity: 'highly_suspicious',
    metadata: {
      sourcePath: '\\\\FILESERVER\\Projects\\confidential_project_proposal.pdf',
      destPath: 'E:\\staging\\',
      fileSize: '2.4 MB',
      copyingProcess: 'explorer.exe',
    },
    relatedEvents: ['evt-004', 'evt-006'],
  },
  {
    id: 'evt-008',
    timestamp: '2026-03-15T08:58:30.000Z',
    action: 'file_created',
    entity: 'E:\\staging\\employee_salary_database.xlsx',
    description: 'Employee salary database copied to USB staging directory.',
    source: 'USN Journal / MFT',
    confidence: 0.96,
    severity: 'critical',
    metadata: {
      sourcePath: '\\\\FILESERVER\\HR\\employee_salary_database.xlsx',
      destPath: 'E:\\staging\\',
      fileSize: '5.1 MB',
      copyingProcess: 'explorer.exe',
    },
    relatedEvents: ['evt-005', 'evt-006'],
  },
  {
    id: 'evt-009',
    timestamp: '2026-03-15T09:05:22.000Z',
    action: 'web_page_visited',
    entity: 'https://www.torproject.org',
    description: 'User visited The Tor Project website from Chrome.',
    source: 'Chrome History / SQLite DB',
    confidence: 0.95,
    severity: 'suspicious',
    metadata: {
      url: 'https://www.torproject.org/download/',
      title: 'Tor Project | Download',
      visitDuration: '4m 32s',
      referrer: 'https://www.google.com/search?q=anonymous+browsing',
    },
    relatedEvents: ['evt-003'],
  },
  {
    id: 'evt-010',
    timestamp: '2026-03-15T09:12:44.000Z',
    action: 'file_downloaded',
    entity: 'tor-browser-install-13.0.14.exe',
    description: 'Tor Browser installer downloaded to Downloads folder.',
    source: 'Chrome History / Zone.Identifier',
    confidence: 0.97,
    severity: 'highly_suspicious',
    metadata: {
      downloadURL: 'https://www.torproject.org/dist/torbrowser/13.0.14/tor-browser-install-13.0.14.exe',
      destPath: 'C:\\Users\\jdoe\\Downloads\\tor-browser-install-13.0.14.exe',
      fileSize: '68.2 MB',
    },
    relatedEvents: ['evt-009'],
  },
  {
    id: 'evt-011',
    timestamp: '2026-03-15T09:18:05.000Z',
    action: 'file_executed',
    entity: 'tor-browser-install-13.0.14.exe',
    description: 'Tor Browser installer executed. Installation completed silently.',
    source: 'Prefetch / Amcache / Shimcache',
    confidence: 0.98,
    severity: 'critical',
    metadata: {
      filePath: 'C:\\Users\\jdoe\\Downloads\\tor-browser-install-13.0.14.exe',
      pid: 7421,
      installPath: 'C:\\Users\\jdoe\\AppData\\Local\\Tor Browser\\',
      signed: true,
      publisher: 'Tor Project',
    },
    relatedEvents: ['evt-010'],
  },
  {
    id: 'evt-012',
    timestamp: '2026-03-15T09:25:33.000Z',
    action: 'network_connection',
    entity: '185.220.101.34:9001 (Tor Directory Authority)',
    description: 'Outbound connection to known Tor directory authority IP address on port 9001.',
    source: 'Network Capture (pcap)',
    confidence: 0.99,
    severity: 'critical',
    metadata: {
      protocol: 'TCP/TLS',
      localPort: 52114,
      remoteIP: '185.220.101.34',
      remotePort: 9001,
      bytesSent: 1024,
      bytesReceived: 4096,
      torNode: true,
    },
    relatedEvents: ['evt-011'],
  },
  {
    id: 'evt-013',
    timestamp: '2026-03-15T09:32:10.000Z',
    action: 'network_connection',
    entity: '185.220.101.42:443 (Tor Relay)',
    description: 'Encrypted outbound connection to Tor relay node.',
    source: 'Network Capture (pcap)',
    confidence: 0.98,
    severity: 'critical',
    metadata: {
      protocol: 'TCP/TLS',
      localPort: 52201,
      remoteIP: '185.220.101.42',
      bytesSent: 65536,
      bytesReceived: 131072,
      torNode: true,
    },
    relatedEvents: ['evt-012'],
  },
  {
    id: 'evt-014',
    timestamp: '2026-03-15T09:45:00.000Z',
    action: 'search_query',
    entity: '"password reset admin panel bypass"',
    description: 'Search query entered in Google Chrome. Query suggests interest in admin panel bypass techniques.',
    source: 'Chrome History (keyword_search_terms)',
    confidence: 0.91,
    severity: 'highly_suspicious',
    metadata: {
      searchEngine: 'google.com',
      searchTerm: 'password reset admin panel bypass',
    },
    relatedEvents: ['evt-003'],
  },
  {
    id: 'evt-015',
    timestamp: '2026-03-15T10:02:18.000Z',
    action: 'web_page_visited',
    entity: 'https://darknetmarketxxxx.onion',
    description: 'Visit to .onion hidden service detected via DNS-over-HTTPS pattern analysis.',
    source: 'Network Capture / Tor circuit analysis',
    confidence: 0.88,
    severity: 'critical',
    metadata: {
      torCircuitId: 'circuit-0x4a2b',
      onionAddress: 'darknetmarketxxxx.onion',
      pageTitle: '[REDACTED]',
      dataTransferred: '4.2 MB',
    },
    relatedEvents: ['evt-012', 'evt-013'],
  },
  {
    id: 'evt-016',
    timestamp: '2026-03-15T10:15:44.000Z',
    action: 'data_exfiltration',
    entity: 'cloud_upload_4.2MB_to_dropbox',
    description: 'Large file upload to Dropbox cloud storage detected via TLS SNI analysis. Estimated 4.2 MB uploaded.',
    source: 'Network Capture / TLS SNI',
    confidence: 0.94,
    severity: 'critical',
    metadata: {
      destination: 'api-content.dropbox.com',
      bytesUploaded: 4_404_019,
      encrypted: true,
      uploadDuration: '18s',
    },
    relatedEvents: ['evt-008'],
  },
  {
    id: 'evt-017',
    timestamp: '2026-03-15T10:30:00.000Z',
    action: 'file_deleted',
    entity: 'C:\\Users\\jdoe\\Downloads\\tor-browser-install-13.0.14.exe',
    description: 'Tor Browser installer deleted from Downloads folder. May indicate anti-forensics attempt.',
    source: 'USN Journal / Recycle Bin',
    confidence: 0.97,
    severity: 'highly_suspicious',
    metadata: {
      fileSize: '68.2 MB',
      deletedFromRecycleBin: true,
      secureDelete: false,
    },
    relatedEvents: ['evt-010', 'evt-011'],
  },
  {
    id: 'evt-018',
    timestamp: '2026-03-15T10:38:22.000Z',
    action: 'file_deleted',
    entity: 'C:\\Users\\jdoe\\AppData\\Local\\Chrome\\User Data\\Default\\History',
    description: 'Chrome browsing history database deleted. Partial recovery possible from $MFT slack space.',
    source: 'USN Journal / $MFT / MFT slack',
    confidence: 0.93,
    severity: 'critical',
    metadata: {
      originalSize: '12.6 MB',
      recoveredEntries: 847,
      deletedFromRecycleBin: true,
    },
    relatedEvents: ['evt-009', 'evt-015'],
  },
  {
    id: 'evt-019',
    timestamp: '2026-03-15T10:42:15.000Z',
    action: 'registry_change',
    entity: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\\USBGuard',
    description: 'Registry run key modified. New entry added to suppress USB device notification popups.',
    source: 'Registry Hive (SYSTEM / SOFTWARE)',
    confidence: 0.91,
    severity: 'highly_suspicious',
    metadata: {
      keyPath: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run',
      valueName: 'USBGuard',
      dataType: 'REG_SZ',
      oldValue: null,
      newValue: '"C:\\Windows\\System32\\rundll32.exe" usbguard.dll,SilentMode',
    },
    relatedEvents: ['evt-006'],
  },
  {
    id: 'evt-020',
    timestamp: '2026-03-15T11:00:05.000Z',
    action: 'file_executed',
    entity: 'secure_delete.exe (sdelete64)',
    description: 'Secure file deletion tool executed with arguments targeting staging area on network share.',
    source: 'Prefetch / PowerShell History',
    confidence: 0.96,
    severity: 'critical',
    metadata: {
      filePath: 'C:\\Tools\\sdelete64.exe',
      arguments: '-s -q \\\\FILESERVER\\Projects\\confidential_project_proposal.pdf',
      passes: 1,
      pid: 8291,
    },
    relatedEvents: ['evt-004', 'evt-007'],
  },
  {
    id: 'evt-021',
    timestamp: '2026-03-15T11:05:30.000Z',
    action: 'file_deleted',
    entity: '\\\\FILESERVER\\Projects\\confidential_project_proposal.pdf',
    description: 'Original confidential file securely deleted from network share. Recovery not possible (DoD 5220.22-M wipe pattern detected).',
    source: 'File Server Audit Log / USN Journal',
    confidence: 0.99,
    severity: 'critical',
    metadata: {
      deletionMethod: 'Secure Delete (sdelete)',
      recoverable: false,
      wipedPasses: 1,
    },
    relatedEvents: ['evt-020'],
  },
  {
    id: 'evt-022',
    timestamp: '2026-03-15T11:15:00.000Z',
    action: 'usb_connected',
    entity: 'SANSA 64GB (USB-SN-789012) — EJECTED',
    description: 'USB device "SANSA 64GB" safely ejected. Total data written: 7.3 MB. Time connected: 2h 29m.',
    source: 'Windows Event Log / USBSTOR',
    confidence: 0.98,
    severity: 'highly_suspicious',
    metadata: {
      serialNumber: 'USB-SN-789012',
      totalBytesWritten: 7_654_604,
      connectDuration: '2h 29m 57s',
      filesCopied: 2,
    },
    relatedEvents: ['evt-006', 'evt-007', 'evt-008'],
  },

  // --- Day 2: March 16, 2026 ---
  {
    id: 'evt-023',
    timestamp: '2026-03-16T08:05:12.000Z',
    action: 'login_attempt',
    entity: 'JDOE\\jdoe',
    description: 'Interactive logon at workstation WS-JDOE-01. Login from IP 10.0.15.42 (different from normal 10.0.15.101).',
    source: 'Windows Security Event Log (4624)',
    confidence: 0.97,
    severity: 'suspicious',
    metadata: {
      logonType: 2,
      sourceIP: '10.0.15.42',
      workstation: 'WS-JDOE-01',
      normalSourceIP: '10.0.15.101',
    },
    relatedEvents: [],
  },
  {
    id: 'evt-024',
    timestamp: '2026-03-16T08:30:00.000Z',
    action: 'file_opened',
    entity: 'source_code_repos.zip',
    description: 'User opened archive containing proprietary source code repositories.',
    source: 'Shellbags / Recent Files',
    confidence: 0.92,
    severity: 'highly_suspicious',
    metadata: {
      filePath: '\\\\DEVSERVER\\Repositories\\source_code_repos.zip',
      fileSize: '1.8 GB',
      archiveContents: 3427,
    },
    relatedEvents: [],
  },
  {
    id: 'evt-025',
    timestamp: '2026-03-16T08:45:22.000Z',
    action: 'file_executed',
    entity: '7z.exe (7-Zip)',
    description: '7-Zip executed to extract source_code_repos.zip to local temp directory.',
    source: 'Prefetch / Amcache',
    confidence: 0.95,
    severity: 'suspicious',
    metadata: {
      filePath: 'C:\\Program Files\\7-Zip\\7z.exe',
      arguments: 'x \\\\DEVSERVER\\Repositories\\source_code_repos.zip -oC:\\Temp\\src_extract\\',
      pid: 8834,
    },
    relatedEvents: ['evt-024'],
  },
  {
    id: 'evt-026',
    timestamp: '2026-03-16T09:00:00.000Z',
    action: 'usb_connected',
    entity: 'Kingston DataTraveler 128GB (USB-SN-445566)',
    description: 'Second USB storage device — Kingston DataTraveler 128GB — connected.',
    source: 'Windows Event Log / USBSTOR',
    confidence: 0.99,
    severity: 'highly_suspicious',
    metadata: {
      deviceID: 'USBSTOR\\Disk&Ven_Kingston&Prod_DataTraveler_3.0&Rev_PQ2\\4455667788990011',
      serialNumber: 'USB-SN-445566',
      driveLetter: 'F:\\',
      capacity: '128 GB',
    },
    relatedEvents: [],
  },
  {
    id: 'evt-027',
    timestamp: '2026-03-16T09:15:33.000Z',
    action: 'file_created',
    entity: 'F:\\acme_source_backup\\src_extract\\',
    description: 'Source code archive extracted and copied to USB drive. 3,427 files totaling 1.8 GB.',
    source: 'USN Journal / $MFT',
    confidence: 0.96,
    severity: 'critical',
    metadata: {
      destPath: 'F:\\acme_source_backup\\',
      totalFiles: 3427,
      totalSize: '1.8 GB',
      duration: '14m 22s',
    },
    relatedEvents: ['evt-024', 'evt-025', 'evt-026'],
  },
  {
    id: 'evt-028',
    timestamp: '2026-03-16T09:35:11.000Z',
    action: 'file_opened',
    entity: 'employee_database.sql',
    description: 'User opened full employee database SQL dump containing 12,847 records.',
    source: 'Shellbags / Jump Lists',
    confidence: 0.93,
    severity: 'critical',
    metadata: {
      filePath: '\\\\DBSERVER\\Backups\\employee_database.sql',
      fileSize: '890 MB',
      recordCount: 12847,
    },
    relatedEvents: [],
  },
  {
    id: 'evt-029',
    timestamp: '2026-03-16T10:00:05.000Z',
    action: 'file_executed',
    entity: 'data_export_tool.exe',
    description: 'Custom data export utility executed. Tool not present in approved software inventory.',
    source: 'Prefetch / Amcache',
    confidence: 0.97,
    severity: 'critical',
    metadata: {
      filePath: 'C:\\Users\\jdoe\\AppData\\Local\\Temp\\data_export_tool.exe',
      pid: 9012,
      arguments: '--source \\\\DBSERVER\\Backups\\employee_database.sql --format csv --dest F:\\acme_source_backup\\',
      signed: false,
      sha256: 'e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0',
    },
    relatedEvents: ['evt-028'],
  },
  {
    id: 'evt-030',
    timestamp: '2026-03-16T10:20:00.000Z',
    action: 'network_connection',
    entity: '203.45.67.89:443 (External — Unknown Cloud Storage)',
    description: 'Outbound TLS connection to external IP 203.45.67.89. SNI indicates cloud storage service.',
    source: 'Network Capture (pcap)',
    confidence: 0.93,
    severity: 'critical',
    metadata: {
      protocol: 'TCP/TLS 1.3',
      localPort: 54321,
      remoteIP: '203.45.67.89',
      remotePort: 443,
      sni: 'files.cloudvault.io',
      bytesSent: 2_097_152,
      bytesReceived: 512,
      ja3Hash: '769,47-53-5-10-49161-49162-49199-49200-49195-49196,0-5-10-11,29-23-24,0',
    },
    relatedEvents: ['evt-029'],
  },
  {
    id: 'evt-031',
    timestamp: '2026-03-16T10:30:00.000Z',
    action: 'data_exfiltration',
    entity: 'large_data_transfer_2.3GB',
    description: 'Large outbound data transfer detected — 2.3 GB sent to external IP 203.45.67.89 over 15 minutes.',
    source: 'Network Capture (pcap) / NetFlow',
    confidence: 0.99,
    severity: 'critical',
    metadata: {
      destinationIP: '203.45.67.89',
      bytesTransferred: 2_469_396_480,
      duration: '15m 33s',
      protocol: 'TLS 1.3',
      avgThroughput: '19.6 Mbps',
    },
    relatedEvents: ['evt-030'],
  },
  {
    id: 'evt-032',
    timestamp: '2026-03-16T10:48:00.000Z',
    action: 'file_executed',
    entity: 'VeraCrypt portable volume creator',
    description: 'VeraCrypt portable executed to create encrypted container on USB drive.',
    source: 'Prefetch / Amcache',
    confidence: 0.97,
    severity: 'critical',
    metadata: {
      filePath: 'F:\\Tools\\VeraCrypt\\VeraCryptPortable.exe',
      pid: 9445,
      arguments: '/c /q /v F:\\hidden_container.hc /s 2048 /p ********',
      containerSize: '2 GB',
      encryption: 'AES-256 + Serpent (cascade)',
    },
    relatedEvents: ['evt-026'],
  },
  {
    id: 'evt-033',
    timestamp: '2026-03-16T11:10:00.000Z',
    action: 'file_executed',
    entity: 'C:\\Tools\\bleachbit_console.exe',
    description: 'BleachBit (anti-forensics tool) run with preset to wipe free space, browser traces, and recently used files.',
    source: 'Prefetch / Amcache / PowerShell History',
    confidence: 0.98,
    severity: 'critical',
    metadata: {
      filePath: 'C:\\Tools\\BleachBit\\bleachbit_console.exe',
      arguments: '--preset internet_explorer.history internet_explorer.cookies system.free_space system.recent_documents',
      operationsCleaned: ['internet_explorer.history', 'internet_explorer.cookies', 'system.free_space', 'system.recent_documents'],
      spaceCleaned: '847 MB',
    },
    relatedEvents: ['evt-018'],
  },
  {
    id: 'evt-034',
    timestamp: '2026-03-16T11:15:00.000Z',
    action: 'registry_change',
    entity: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\Count',
    description: 'UserAssist registry key cleared to remove evidence of recently accessed programs and files.',
    source: 'Registry Hive (NTUSER.DAT)',
    confidence: 0.94,
    severity: 'critical',
    metadata: {
      keyPath: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\{CEBFF5CD-ACE2-4F16-FB23-5765174A5A82}\\Count',
      oldValue: '14 entries',
      newValue: '0 entries (cleared)',
    },
    relatedEvents: ['evt-033'],
  },
  {
    id: 'evt-035',
    timestamp: '2026-03-16T11:20:00.000Z',
    action: 'registry_change',
    entity: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBSTOR\\Start',
    description: 'USB storage driver disabled via registry to prevent future USB connection logging.',
    source: 'Registry Hive (SYSTEM)',
    confidence: 0.92,
    severity: 'highly_suspicious',
    metadata: {
      keyPath: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBSTOR',
      valueName: 'Start',
      oldValue: 3,
      newValue: 4,
      effect: 'USB storage devices disabled on next boot',
    },
    relatedEvents: ['evt-006', 'evt-026'],
  },
  {
    id: 'evt-036',
    timestamp: '2026-03-16T11:30:00.000Z',
    action: 'service_start',
    entity: 'ShadowCopySuppressor (shadowcopy_svc.dll)',
    description: 'Unknown service "ShadowCopySuppressor" installed and started. Designed to disable Volume Shadow Copy Service.',
    source: 'Windows Event Log (7045) / Registry',
    confidence: 0.96,
    severity: 'critical',
    metadata: {
      serviceName: 'ShadowCopySuppressor',
      binaryPath: 'C:\\Windows\\System32\\shadowcopy_svc.dll',
      serviceType: 'kernel',
      startType: 'auto',
      signed: false,
      sha256: 'f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e2',
    },
    relatedEvents: [],
  },
  {
    id: 'evt-037',
    timestamp: '2026-03-16T14:20:00.000Z',
    action: 'login_attempt',
    entity: 'JDOE\\jdoe',
    description: 'User re-authenticated after extended absence (lunch break).',
    source: 'Windows Security Event Log (4624)',
    confidence: 0.97,
    severity: 'benign',
    metadata: { logonType: 7, workstation: 'WS-JDOE-01' },
    relatedEvents: [],
  },
  {
    id: 'evt-038',
    timestamp: '2026-03-16T14:35:00.000Z',
    action: 'search_query',
    entity: '"bitcoin wallet anonymous purchase prepaid"',
    description: 'Search query related to anonymous Bitcoin wallet creation.',
    source: 'Chrome History (keyword_search_terms)',
    confidence: 0.89,
    severity: 'highly_suspicious',
    metadata: { searchEngine: 'duckduckgo.com', searchTerm: 'bitcoin wallet anonymous purchase prepaid' },
    relatedEvents: [],
  },
  {
    id: 'evt-039',
    timestamp: '2026-03-16T14:50:00.000Z',
    action: 'web_page_visited',
    entity: 'https://localbitcoins.com/buy-bitcoins-online',
    description: 'Visit to peer-to-peer Bitcoin marketplace. Potentially setting up anonymous financial channel.',
    source: 'Chrome History / Network Capture',
    confidence: 0.90,
    severity: 'suspicious',
    metadata: { url: 'https://localbitcoins.com/buy-bitcoins-online/cash-by-mail/', visitDuration: '8m 12s' },
    relatedEvents: ['evt-038'],
  },
  {
    id: 'evt-040',
    timestamp: '2026-03-16T15:05:00.000Z',
    action: 'file_executed',
    entity: 'puttygen.exe (SSH Key Generator)',
    description: 'PuTTYgen executed to generate new SSH key pair. SSH keys can be used to maintain persistent access.',
    source: 'Prefetch / Amcache',
    confidence: 0.95,
    severity: 'highly_suspicious',
    metadata: {
      filePath: 'C:\\Tools\\PuTTY\\puttygen.exe',
      pid: 10234,
      keyType: 'RSA-4096',
      keyComment: 'backup@acmecorp.com',
    },
    relatedEvents: [],
  },
  {
    id: 'evt-041',
    timestamp: '2026-03-16T15:20:00.000Z',
    action: 'file_created',
    entity: 'F:\\keys\\ssh_key_backup.ppk',
    description: 'SSH private key exported and saved to USB drive. Key comment: backup@acmecorp.com.',
    source: 'USN Journal',
    confidence: 0.95,
    severity: 'critical',
    metadata: {
      filePath: 'F:\\keys\\ssh_key_backup.ppk',
      keyType: 'RSA-4096',
      passphraseProtected: false,
    },
    relatedEvents: ['evt-040', 'evt-026'],
  },
  {
    id: 'evt-042',
    timestamp: '2026-03-16T15:45:00.000Z',
    action: 'driver_loaded',
    entity: 'rootkit_filter.sys (Unknown Kernel Driver)',
    description: 'Unknown kernel-mode driver loaded. Digital signature invalid. Classified as potential rootkit.',
    source: 'Windows Event Log (7045) / Driver Store',
    confidence: 0.88,
    severity: 'critical',
    metadata: {
      driverPath: 'C:\\Windows\\System32\\drivers\\rootkit_filter.sys',
      signed: false,
      publisher: 'Microsoft Windows',
      signatureStatus: 'INVALID — Certificate chain broken',
      sha256: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
    },
    relatedEvents: [],
  },
  {
    id: 'evt-043',
    timestamp: '2026-03-16T16:00:00.000Z',
    action: 'usb_connected',
    entity: 'Kingston DataTraveler 128GB (USB-SN-445566) — EJECTED',
    description: 'Second USB device ejected. Total data written: 4.1 GB. Time connected: 7h 0m.',
    source: 'Windows Event Log / USBSTOR',
    confidence: 0.98,
    severity: 'highly_suspicious',
    metadata: {
      serialNumber: 'USB-SN-445566',
      totalBytesWritten: 4_404_019_200,
      connectDuration: '7h 0m 0s',
      filesCopied: 3431,
    },
    relatedEvents: ['evt-026', 'evt-027', 'evt-041'],
  },
  {
    id: 'evt-044',
    timestamp: '2026-03-16T16:15:00.000Z',
    action: 'system_shutdown',
    entity: 'WS-JDOE-01',
    description: 'System shutdown initiated by user jdoe. Normal shutdown type.',
    source: 'Windows Event Log (1074)',
    confidence: 0.99,
    severity: 'benign',
    metadata: { shutdownType: 'user initiated', initiator: 'jdoe' },
    relatedEvents: [],
  },

  // --- Day 3: March 17, 2026 ---
  {
    id: 'evt-045',
    timestamp: '2026-03-17T07:50:00.000Z',
    action: 'login_attempt',
    entity: 'JDOE\\jdoe',
    description: 'Early morning login. User logged in 40 minutes earlier than usual.',
    source: 'Windows Security Event Log (4624)',
    confidence: 0.97,
    severity: 'suspicious',
    metadata: { logonType: 2, workstation: 'WS-JDOE-01', usualLoginTime: '08:30' },
    relatedEvents: [],
  },
  {
    id: 'evt-046',
    timestamp: '2026-03-17T08:10:00.000Z',
    action: 'file_modified',
    entity: '.ssh/authorized_keys',
    description: 'SSH authorized_keys file modified on remote Linux server DEV-SERVER-03 via SSH connection.',
    source: 'DEV-SERVER-03 SSH Auth Log / auditd',
    confidence: 0.91,
    severity: 'critical',
    metadata: {
      server: 'dev-server-03.acmecorp.internal',
      sshUser: 'deploy',
      sourceIP: '10.0.15.101',
      keyAdded: 'RSA-4096 backup@acmecorp.com',
    },
    relatedEvents: ['evt-040', 'evt-041'],
  },
  {
    id: 'evt-047',
    timestamp: '2026-03-17T08:25:00.000Z',
    action: 'registry_change',
    entity: 'HKLM\\SOFTWARE\\AcmeCorp\\AppConfig\\DbConnectionString',
    description: 'Database connection string in application config modified to point to external server.',
    source: 'Registry Hive (SOFTWARE) / Application Logs',
    confidence: 0.90,
    severity: 'critical',
    metadata: {
      keyPath: 'HKLM\\SOFTWARE\\AcmeCorp\\AppConfig',
      valueName: 'DbConnectionString',
      oldValue: 'Server=DB-PROD-01;Database=MainDB;Trusted_Connection=True',
      newValue: 'Server=203.45.67.89,1433;Database=MainDB;User ID=sa;Password=********',
    },
    relatedEvents: ['evt-030'],
  },
];

// =============================================================================
// REWIND SEQUENCE (28 events — chronological narrative)
// =============================================================================

const rewindSequence: RewindEvent[] = [
  {
    id: 'rwd-001',
    timestamp: '2026-03-15T08:12:33.000Z',
    action: 'login_attempt',
    entity: 'JDOE\\jdoe logged into WS-JDOE-01',
    user: 'John Doe',
    description: 'User logged into workstation from local session.',
    source: 'Security Event Log',
    confidence: 0.98,
    icon: 'LogIn',
    color: '#0ea5e9',
  },
  {
    id: 'rwd-002',
    timestamp: '2026-03-15T08:22:10.000Z',
    action: 'browser_opened',
    entity: 'Google Chrome launched',
    user: 'John Doe',
    description: 'Chrome browser opened.',
    source: 'Prefetch',
    confidence: 0.95,
    icon: 'Globe',
    color: '#06b6d4',
  },
  {
    id: 'rwd-003',
    timestamp: '2026-03-15T08:30:45.000Z',
    action: 'file_opened',
    entity: 'confidential_project_proposal.pdf',
    user: 'John Doe',
    description: 'Opened confidential project proposal from network file server.',
    source: 'Jump Lists',
    confidence: 0.93,
    icon: 'FileText',
    color: '#6366f1',
  },
  {
    id: 'rwd-004',
    timestamp: '2026-03-15T08:42:18.000Z',
    action: 'file_opened',
    entity: 'employee_salary_database.xlsx',
    user: 'John Doe',
    description: 'Opened employee salary database from HR shared folder.',
    source: 'Recent Files',
    confidence: 0.92,
    icon: 'FileText',
    color: '#6366f1',
  },
  {
    id: 'rwd-005',
    timestamp: '2026-03-15T08:45:03.000Z',
    action: 'usb_connected',
    entity: 'SANSA 64GB USB drive connected',
    user: 'John Doe',
    description: 'USB mass storage device inserted. Assigned drive E:\\.',
    source: 'USBSTOR Registry',
    confidence: 0.99,
    icon: 'Usb',
    color: '#059669',
  },
  {
    id: 'rwd-006',
    timestamp: '2026-03-15T08:52:11.000Z',
    action: 'file_created',
    entity: 'Confidential files copied to USB',
    user: 'John Doe',
    description: 'Copied confidential_project_proposal.pdf to E:\\staging\\',
    source: 'USN Journal',
    confidence: 0.96,
    icon: 'FilePlus',
    color: '#22c55e',
  },
  {
    id: 'rwd-007',
    timestamp: '2026-03-15T08:58:30.000Z',
    action: 'file_created',
    entity: 'Employee salary data copied to USB',
    user: 'John Doe',
    description: 'Copied employee_salary_database.xlsx to E:\\staging\\',
    source: 'USN Journal',
    confidence: 0.96,
    icon: 'FilePlus',
    color: '#22c55e',
  },
  {
    id: 'rwd-008',
    timestamp: '2026-03-15T09:05:22.000Z',
    action: 'web_page_visited',
    entity: 'Visited torproject.org',
    user: 'John Doe',
    description: 'Navigated to Tor Project download page.',
    source: 'Chrome History',
    confidence: 0.95,
    icon: 'ExternalLink',
    color: '#14b8a6',
  },
  {
    id: 'rwd-009',
    timestamp: '2026-03-15T09:12:44.000Z',
    action: 'file_downloaded',
    entity: 'Downloaded tor-browser-install.exe',
    user: 'John Doe',
    description: 'Downloaded Tor Browser installer (68.2 MB).',
    source: 'Chrome History',
    confidence: 0.97,
    icon: 'Download',
    color: '#3b82f6',
  },
  {
    id: 'rwd-010',
    timestamp: '2026-03-15T09:18:05.000Z',
    action: 'file_executed',
    entity: 'Installed Tor Browser',
    user: 'John Doe',
    description: 'Executed Tor Browser installer silently.',
    source: 'Prefetch / Amcache',
    confidence: 0.98,
    icon: 'Play',
    color: '#dc2626',
  },
  {
    id: 'rwd-011',
    timestamp: '2026-03-15T09:25:33.000Z',
    action: 'network_connection',
    entity: 'Connected to Tor network (185.220.101.34)',
    user: 'John Doe',
    description: 'Established connection to Tor directory authority.',
    source: 'Network Capture',
    confidence: 0.99,
    icon: 'Wifi',
    color: '#ec4899',
  },
  {
    id: 'rwd-012',
    timestamp: '2026-03-15T09:32:10.000Z',
    action: 'network_connection',
    entity: 'Tor relay connection (185.220.101.42)',
    user: 'John Doe',
    description: 'Encrypted traffic routed through Tor relay node.',
    source: 'Network Capture',
    confidence: 0.98,
    icon: 'Wifi',
    color: '#ec4899',
  },
  {
    id: 'rwd-013',
    timestamp: '2026-03-15T09:45:00.000Z',
    action: 'search_query',
    entity: 'Searched "password reset admin panel bypass"',
    user: 'John Doe',
    description: 'Entered suspicious search query in Chrome.',
    source: 'Chrome History',
    confidence: 0.91,
    icon: 'Search',
    color: '#8b5cf6',
  },
  {
    id: 'rwd-014',
    timestamp: '2026-03-15T10:02:18.000Z',
    action: 'web_page_visited',
    entity: 'Visited .onion hidden service',
    user: 'John Doe',
    description: 'Accessed darknet marketplace via Tor hidden service.',
    source: 'Tor circuit analysis',
    confidence: 0.88,
    icon: 'ExternalLink',
    color: '#14b8a6',
  },
  {
    id: 'rwd-015',
    timestamp: '2026-03-15T10:15:44.000Z',
    action: 'data_exfiltration',
    entity: 'Uploaded data to Dropbox',
    user: 'John Doe',
    description: '4.2 MB uploaded to cloud storage via Dropbox API.',
    source: 'Network Capture',
    confidence: 0.94,
    icon: 'Upload',
    color: '#dc2626',
  },
  {
    id: 'rwd-016',
    timestamp: '2026-03-15T10:30:00.000Z',
    action: 'file_deleted',
    entity: 'Deleted Tor installer from Downloads',
    user: 'John Doe',
    description: 'Tor Browser installer removed from Downloads folder.',
    source: 'USN Journal',
    confidence: 0.97,
    icon: 'Trash2',
    color: '#ef4444',
  },
  {
    id: 'rwd-017',
    timestamp: '2026-03-15T10:38:22.000Z',
    action: 'file_deleted',
    entity: 'Cleared Chrome browsing history',
    user: 'John Doe',
    description: 'Chrome History database deleted.',
    source: 'USN Journal',
    confidence: 0.93,
    icon: 'Trash2',
    color: '#ef4444',
  },
  {
    id: 'rwd-018',
    timestamp: '2026-03-15T10:42:15.000Z',
    action: 'registry_change',
    entity: 'Modified registry to suppress USB notifications',
    user: 'John Doe',
    description: 'Added run key to suppress USB device alerts.',
    source: 'Registry',
    confidence: 0.91,
    icon: 'Settings',
    color: '#d97706',
  },
  {
    id: 'rwd-019',
    timestamp: '2026-03-15T11:00:05.000Z',
    action: 'file_executed',
    entity: 'Ran secure_delete on original files',
    user: 'John Doe',
    description: 'Executed sdelete64 to wipe confidential files from file server.',
    source: 'Prefetch / PS History',
    confidence: 0.96,
    icon: 'Play',
    color: '#dc2626',
  },
  {
    id: 'rwd-020',
    timestamp: '2026-03-15T11:05:30.000Z',
    action: 'file_deleted',
    entity: 'Original confidential file securely wiped',
    user: 'John Doe',
    description: 'confidential_project_proposal.pdf securely deleted from network share.',
    source: 'File Server Audit',
    confidence: 0.99,
    icon: 'Trash2',
    color: '#ef4444',
  },
  {
    id: 'rwd-021',
    timestamp: '2026-03-15T11:15:00.000Z',
    action: 'usb_connected',
    entity: 'SANSA USB drive ejected',
    user: 'John Doe',
    description: 'USB device ejected. 7.3 MB total data written during 2h 30m session.',
    source: 'USBSTOR',
    confidence: 0.98,
    icon: 'Usb',
    color: '#059669',
  },
  {
    id: 'rwd-022',
    timestamp: '2026-03-16T08:30:00.000Z',
    action: 'file_opened',
    entity: 'Opened source_code_repos.zip (1.8 GB)',
    user: 'John Doe',
    description: 'Opened proprietary source code archive from development server.',
    source: 'Shellbags',
    confidence: 0.92,
    icon: 'FileText',
    color: '#6366f1',
  },
  {
    id: 'rwd-023',
    timestamp: '2026-03-16T09:15:33.000Z',
    action: 'file_created',
    entity: 'Copied source code to Kingston USB drive',
    user: 'John Doe',
    description: '3,427 source files (1.8 GB) copied to second USB device.',
    source: 'USN Journal',
    confidence: 0.96,
    icon: 'FilePlus',
    color: '#22c55e',
  },
  {
    id: 'rwd-024',
    timestamp: '2026-03-16T10:30:00.000Z',
    action: 'data_exfiltration',
    entity: 'Large data transfer to external IP (2.3 GB)',
    user: 'John Doe',
    description: '2.3 GB exfiltrated to 203.45.67.89 over TLS.',
    source: 'Network Capture',
    confidence: 0.99,
    icon: 'Upload',
    color: '#dc2626',
  },
  {
    id: 'rwd-025',
    timestamp: '2026-03-16T10:48:00.000Z',
    action: 'file_executed',
    entity: 'Created VeraCrypt encrypted container on USB',
    user: 'John Doe',
    description: 'Created 2 GB AES-256 encrypted container on USB drive.',
    source: 'Prefetch',
    confidence: 0.97,
    icon: 'Play',
    color: '#dc2626',
  },
  {
    id: 'rwd-026',
    timestamp: '2026-03-16T11:10:00.000Z',
    action: 'file_executed',
    entity: 'Ran BleachBit to clean traces',
    user: 'John Doe',
    description: 'BleachBit used to wipe browser traces, free space, and recent docs.',
    source: 'Prefetch',
    confidence: 0.98,
    icon: 'Terminal',
    color: '#f97316',
  },
  {
    id: 'rwd-027',
    timestamp: '2026-03-16T11:30:00.000Z',
    action: 'service_start',
    entity: 'Installed ShadowCopySuppressor service',
    user: 'John Doe',
    description: 'Installed and started unsigned kernel service to disable VSS.',
    source: 'Event Log (7045)',
    confidence: 0.96,
    icon: 'Cog',
    color: '#e11d48',
  },
  {
    id: 'rwd-028',
    timestamp: '2026-03-17T08:10:00.000Z',
    action: 'registry_change',
    entity: 'Added SSH key to remote server',
    user: 'John Doe',
    description: 'Modified authorized_keys on DEV-SERVER-03 for persistent access.',
    source: 'SSH Auth Log',
    confidence: 0.91,
    icon: 'Settings',
    color: '#d97706',
  },
];

// =============================================================================
// CORRELATION GRAPH (18 nodes, 28 edges)
// =============================================================================

const correlationGraph: CorrelationGraph = {
  nodes: [
    {
      id: 'node-001',
      type: 'user',
      label: 'John Doe (jdoe@acmecorp.com)',
      properties: { department: 'Engineering', role: 'Senior Developer', employeeId: 'EMP-2847' },
      severity: 'critical',
    },
    {
      id: 'node-002',
      type: 'file',
      label: 'confidential_project_proposal.pdf',
      properties: { path: '\\\\FILESERVER\\Projects\\', size: '2.4 MB', status: 'deleted' },
      severity: 'critical',
    },
    {
      id: 'node-003',
      type: 'file',
      label: 'employee_salary_database.xlsx',
      properties: { path: '\\\\FILESERVER\\HR\\', size: '5.1 MB', records: 12847 },
      severity: 'critical',
    },
    {
      id: 'node-004',
      type: 'file',
      label: 'source_code_repos.zip',
      properties: { path: '\\\\DEVSERVER\\Repositories\\', size: '1.8 GB', files: 3427 },
      severity: 'critical',
    },
    {
      id: 'node-005',
      type: 'file',
      label: 'employee_database.sql',
      properties: { path: '\\\\DBSERVER\\Backups\\', size: '890 MB', records: 12847 },
      severity: 'critical',
    },
    {
      id: 'node-006',
      type: 'process',
      label: 'tor-browser-install.exe',
      properties: { version: '13.0.14', publisher: 'Tor Project', status: 'installed_then_deleted' },
      severity: 'critical',
    },
    {
      id: 'node-007',
      type: 'process',
      label: 'sdelete64.exe',
      properties: { path: 'C:\\Tools\\sdelete64.exe', purpose: 'Secure file deletion' },
      severity: 'critical',
    },
    {
      id: 'node-008',
      type: 'process',
      label: 'data_export_tool.exe',
      properties: { path: 'C:\\Users\\jdoe\\AppData\\Local\\Temp\\', signed: false },
      severity: 'critical',
    },
    {
      id: 'node-009',
      type: 'process',
      label: 'VeraCryptPortable.exe',
      properties: { containerSize: '2 GB', encryption: 'AES-256 + Serpent' },
      severity: 'critical',
    },
    {
      id: 'node-010',
      type: 'process',
      label: 'bleachbit_console.exe',
      properties: { path: 'C:\\Tools\\BleachBit\\', spaceCleaned: '847 MB' },
      severity: 'critical',
    },
    {
      id: 'node-011',
      type: 'ip',
      label: '185.220.101.34',
      properties: { type: 'Tor Directory Authority', port: 9001, country: 'Germany' },
      severity: 'critical',
    },
    {
      id: 'node-012',
      type: 'ip',
      label: '185.220.101.42',
      properties: { type: 'Tor Relay Node', port: 443, country: 'Germany' },
      severity: 'critical',
    },
    {
      id: 'node-013',
      type: 'ip',
      label: '203.45.67.89',
      properties: { type: 'External Cloud Storage', sni: 'files.cloudvault.io', country: 'Russia' },
      severity: 'critical',
    },
    {
      id: 'node-014',
      type: 'domain',
      label: 'torproject.org',
      properties: { category: 'Anonymization', risk: 'high' },
      severity: 'highly_suspicious',
    },
    {
      id: 'node-015',
      type: 'url',
      label: 'darknetmarketxxxx.onion',
      properties: { category: 'Darknet Marketplace', protocol: 'Tor Hidden Service' },
      severity: 'critical',
    },
    {
      id: 'node-016',
      type: 'artifact',
      label: 'SANSA 64GB USB (USB-SN-789012)',
      properties: { driveLetter: 'E:\\', dataWritten: '7.3 MB', fileSystem: 'exFAT' },
      severity: 'highly_suspicious',
    },
    {
      id: 'node-017',
      type: 'artifact',
      label: 'Kingston 128GB USB (USB-SN-445566)',
      properties: { driveLetter: 'F:\\', dataWritten: '4.1 GB', fileSystem: 'NTFS' },
      severity: 'critical',
    },
    {
      id: 'node-018',
      type: 'registry',
      label: 'HKLM\\...\\Services\\ShadowCopySuppressor',
      properties: { binaryPath: 'shadowcopy_svc.dll', signed: false, purpose: 'Disable VSS' },
      severity: 'critical',
    },
  ],
  edges: [
    { source: 'node-001', target: 'node-002', relation: 'accessed', weight: 0.95, timestamp: '2026-03-15T08:30:45.000Z' },
    { source: 'node-001', target: 'node-003', relation: 'accessed', weight: 0.92, timestamp: '2026-03-15T08:42:18.000Z' },
    { source: 'node-001', target: 'node-004', relation: 'accessed', weight: 0.93, timestamp: '2026-03-16T08:30:00.000Z' },
    { source: 'node-001', target: 'node-005', relation: 'accessed', weight: 0.93, timestamp: '2026-03-16T09:35:11.000Z' },
    { source: 'node-001', target: 'node-006', relation: 'downloaded_and_executed', weight: 0.98, timestamp: '2026-03-15T09:12:44.000Z' },
    { source: 'node-001', target: 'node-007', relation: 'executed', weight: 0.96, timestamp: '2026-03-15T11:00:05.000Z' },
    { source: 'node-001', target: 'node-008', relation: 'executed', weight: 0.97, timestamp: '2026-03-16T10:00:05.000Z' },
    { source: 'node-001', target: 'node-009', relation: 'executed', weight: 0.97, timestamp: '2026-03-16T10:48:00.000Z' },
    { source: 'node-001', target: 'node-010', relation: 'executed', weight: 0.98, timestamp: '2026-03-16T11:10:00.000Z' },
    { source: 'node-001', target: 'node-016', relation: 'connected_usb', weight: 0.99, timestamp: '2026-03-15T08:45:03.000Z' },
    { source: 'node-001', target: 'node-017', relation: 'connected_usb', weight: 0.99, timestamp: '2026-03-16T09:00:00.000Z' },
    { source: 'node-001', target: 'node-018', relation: 'installed', weight: 0.96, timestamp: '2026-03-16T11:30:00.000Z' },
    { source: 'node-002', target: 'node-016', relation: 'copied_to', weight: 0.96, timestamp: '2026-03-15T08:52:11.000Z' },
    { source: 'node-003', target: 'node-016', relation: 'copied_to', weight: 0.96, timestamp: '2026-03-15T08:58:30.000Z' },
    { source: 'node-004', target: 'node-017', relation: 'copied_to', weight: 0.96, timestamp: '2026-03-16T09:15:33.000Z' },
    { source: 'node-005', target: 'node-017', relation: 'copied_to', weight: 0.95, timestamp: '2026-03-16T10:00:05.000Z' },
    { source: 'node-006', target: 'node-011', relation: 'connected_to', weight: 0.99, timestamp: '2026-03-15T09:25:33.000Z' },
    { source: 'node-006', target: 'node-012', relation: 'connected_to', weight: 0.98, timestamp: '2026-03-15T09:32:10.000Z' },
    { source: 'node-006', target: 'node-014', relation: 'downloaded_from', weight: 0.95, timestamp: '2026-03-15T09:05:22.000Z' },
    { source: 'node-006', target: 'node-015', relation: 'accessed_via_tor', weight: 0.88, timestamp: '2026-03-15T10:02:18.000Z' },
    { source: 'node-007', target: 'node-002', relation: 'deleted', weight: 0.99, timestamp: '2026-03-15T11:05:30.000Z' },
    { source: 'node-008', target: 'node-005', relation: 'exported', weight: 0.97, timestamp: '2026-03-16T10:00:05.000Z' },
    { source: 'node-008', target: 'node-013', relation: 'uploaded_to', weight: 0.99, timestamp: '2026-03-16T10:30:00.000Z' },
    { source: 'node-009', target: 'node-017', relation: 'created_on', weight: 0.97, timestamp: '2026-03-16T10:48:00.000Z' },
    { source: 'node-010', target: 'node-014', relation: 'cleaned_traces_of', weight: 0.93, timestamp: '2026-03-16T11:10:00.000Z' },
    { source: 'node-011', target: 'node-012', relation: 'tor_circuit', weight: 0.95, timestamp: '2026-03-15T09:32:10.000Z' },
    { source: 'node-015', target: 'node-013', relation: 'potentially_uploaded_to', weight: 0.82, timestamp: '2026-03-15T10:15:44.000Z' },
    { source: 'node-017', target: 'node-013', relation: 'data_exfiltrated_to', weight: 0.99, timestamp: '2026-03-16T10:30:00.000Z' },
    { source: 'node-018', target: 'node-010', relation: 'anti_forensics_pair', weight: 0.94, timestamp: '2026-03-16T11:30:00.000Z' },
  ],
};

// =============================================================================
// SUSPICIOUS FINDINGS (15 findings)
// =============================================================================

const suspiciousFindings: SuspiciousFinding[] = [
  {
    id: 'find-001',
    severity: 'critical',
    category: 'Data Exfiltration',
    title: 'Massive Data Exfiltration to External Server',
    description:
      'A total of 2.3 GB of data was transferred to external IP 203.45.67.89 (hosting files.cloudvault.io) over TLS 1.3 on March 16, 2026 at 10:30. The transfer lasted 15 minutes with an average throughput of 19.6 Mbps. This volume far exceeds normal user activity patterns.',
    evidence: 'Network Capture (pcap) / evt-031',
    timestamp: '2026-03-16T10:30:00.000Z',
    relatedArtifacts: ['evt-029', 'evt-030', 'node-008', 'node-013'],
    confidence: 0.99,
    recommendation:
      'Immediately block IP 203.45.67.89 at the corporate firewall. Issue emergency disclosure if PII was included. Contact the hosting provider for server takedown. Preserve the pcap for chain of custody.',
  },
  {
    id: 'find-002',
    severity: 'critical',
    category: 'Anti-Forensics',
    title: 'Secure Deletion of Confidential Files',
    description:
      'sdelete64.exe was used to securely wipe the original confidential_project_proposal.pdf from the network file share. The file was overwritten using a DoD 5220.22-M compliant pattern, making recovery impossible. This was performed after the file was copied to USB storage.',
    evidence: 'Prefetch / PowerShell History / evt-020, evt-021',
    timestamp: '2026-03-15T11:00:05.000Z',
    relatedArtifacts: ['evt-004', 'evt-007', 'evt-021', 'node-002', 'node-007'],
    confidence: 0.99,
    recommendation:
      'Document the anti-forensics attempt. Check file server for any surviving shadow copies or backup snapshots. The deletion pattern itself is strong circumstantial evidence of intent.',
  },
  {
    id: 'find-003',
    severity: 'critical',
    category: 'Removable Media',
    title: 'USB Mass Storage Exfiltration — 4.1 GB to Kingston Drive',
    description:
      'Over 4.1 GB of data was copied to a Kingston DataTraveler 128GB USB drive (USB-SN-445566) on March 16. The data included the complete proprietary source code repository (3,427 files) and an encrypted VeraCrypt container. The USB drive was connected for 7 hours.',
    evidence: 'USBSTOR Registry / USN Journal / evt-026, evt-027, evt-043',
    timestamp: '2026-03-16T09:15:33.000Z',
    relatedArtifacts: ['evt-024', 'evt-025', 'evt-026', 'evt-032', 'node-004', 'node-009', 'node-017'],
    confidence: 0.98,
    recommendation:
      'The Kingston USB drive (USB-SN-445566) must be located and seized immediately. Attempt to image the drive and crack the VeraCrypt container if possible. Check physical access logs for the device.',
  },
  {
    id: 'find-004',
    severity: 'critical',
    category: 'Network',
    title: 'Tor Network Usage — Known Directory Authority Contact',
    description:
      'The subject connected to Tor directory authority 185.220.101.34 (port 9001) and Tor relay 185.220.101.42 (port 443) on March 15. The Tor Browser was installed from torproject.org and used to access .onion hidden services, including a darknet marketplace.',
    evidence: 'Network Capture / Chrome History / evt-009 through evt-015',
    timestamp: '2026-03-15T09:25:33.000Z',
    relatedArtifacts: ['evt-009', 'evt-010', 'evt-011', 'evt-012', 'evt-013', 'evt-015', 'node-006', 'node-011', 'node-012'],
    confidence: 0.98,
    recommendation:
      'Implement Tor blocking at the network level. The use of Tor + darknet marketplace access suggests potential intent to sell stolen data or purchase additional tools. Coordinate with law enforcement.',
  },
  {
    id: 'find-005',
    severity: 'critical',
    category: 'Persistence',
    title: 'Unsigned Kernel Driver Loaded — Potential Rootkit',
    description:
      'An unsigned kernel-mode driver (rootkit_filter.sys) was loaded on March 16 at 15:45. The driver has an invalid digital signature (certificate chain broken) and was not found in the approved software inventory. This may be a rootkit used to maintain persistent, stealthy access.',
    evidence: 'Windows Event Log (7045) / Driver Store / evt-042',
    timestamp: '2026-03-16T15:45:00.000Z',
    relatedArtifacts: ['evt-042', 'node-018'],
    confidence: 0.88,
    recommendation:
      'Isolate the workstation immediately. Submit rootkit_filter.sys for reverse engineering. Perform full memory acquisition for volatile artifact analysis. Consider wiping and reimaging the system.',
  },
  {
    id: 'find-006',
    severity: 'critical',
    category: 'Anti-Forensics',
    title: 'BleachBit Used to Clean Digital Traces',
    description:
      'BleachBit was executed with aggressive presets to wipe browser history, cookies, free space, and recently used documents. A total of 847 MB was cleaned. Combined with UserAssist registry key clearing and shadow copy disabling, this represents a coordinated anti-forensics campaign.',
    evidence: 'Prefetch / Registry / evt-033, evt-034',
    timestamp: '2026-03-16T11:10:00.000Z',
    relatedArtifacts: ['evt-033', 'evt-034', 'evt-036', 'node-010', 'node-018'],
    confidence: 0.98,
    recommendation:
      'The anti-forensics activity itself is strong evidence of criminal intent. Attempt recovery from $MFT slack space, unallocated space, and hibernation/page files. Document the cleaning timeline.',
  },
  {
    id: 'find-007',
    severity: 'critical',
    category: 'Credential Compromise',
    title: 'SSH Key Backdoor on Production Server',
    description:
      'An RSA-4096 SSH key was generated and exported to USB. The corresponding public key was then added to the authorized_keys file on DEV-SERVER-03, granting persistent SSH access. The key was unprotected (no passphrase).',
    evidence: 'SSH Auth Log (dev-server-03) / evt-040, evt-041, evt-046',
    timestamp: '2026-03-17T08:10:00.000Z',
    relatedArtifacts: ['evt-040', 'evt-041', 'evt-046', 'node-017'],
    confidence: 0.94,
    recommendation:
      'Immediately remove the unauthorized SSH key from DEV-SERVER-03. Audit all servers for unauthorized SSH keys. Reset all service account credentials. Review access logs for suspicious SSH connections.',
  },
  {
    id: 'find-008',
    severity: 'critical',
    category: 'Database Tampering',
    title: 'Database Connection String Redirected to External Server',
    description:
      'The application database connection string in the registry was modified to point from the internal DB-PROD-01 server to external IP 203.45.67.89 with SQL authentication credentials. This would redirect all application database queries to an attacker-controlled server.',
    evidence: 'Registry Hive (SOFTWARE) / evt-047',
    timestamp: '2026-03-17T08:25:00.000Z',
    relatedArtifacts: ['evt-030', 'evt-031', 'evt-047', 'node-013'],
    confidence: 0.90,
    recommendation:
      'Revert the registry change immediately. Verify the current connection string across all servers. Audit the external IP for intercepted database credentials. Review application logs for redirected queries.',
  },
  {
    id: 'find-009',
    severity: 'highly_suspicious',
    category: 'Darknet Activity',
    title: 'Access to Darknet Marketplace (.onion)',
    description:
      'A .onion hidden service (darknetmarketxxxx.onion) was accessed via Tor. The page title is redacted but 4.2 MB of data was transferred during the visit. This is consistent with browsing a marketplace for purchasing illegal goods or services.',
    evidence: 'Tor Circuit Analysis / evt-015',
    timestamp: '2026-03-15T10:02:18.000Z',
    relatedArtifacts: ['evt-012', 'evt-013', 'evt-015', 'node-015'],
    confidence: 0.88,
    recommendation:
      'Document the .onion access for the investigation report. If possible, attempt to identify the marketplace through Tor directory correlation. Coordinate with law enforcement for potential darknet investigation.',
  },
  {
    id: 'find-010',
    severity: 'highly_suspicious',
    category: 'Removable Media',
    title: 'USB Device Usage — SANSA 64GB (7.3 MB Exfiltrated)',
    description:
      'A SANSA 64GB USB drive was connected for 2 hours and 30 minutes. Two confidential files were copied to a staging directory: confidential_project_proposal.pdf and employee_salary_database.xlsx. USB notification suppression was subsequently enabled.',
    evidence: 'USBSTOR / USN Journal / evt-006, evt-007, evt-008',
    timestamp: '2026-03-15T08:45:03.000Z',
    relatedArtifacts: ['evt-006', 'evt-007', 'evt-008', 'evt-019', 'node-002', 'node-003', 'node-016'],
    confidence: 0.96,
    recommendation:
      'Locate and forensically image the SANSA USB drive (USB-SN-789012). Compare file hashes on the USB with the originals to confirm data match. Document the USB suppression registry change.',
  },
  {
    id: 'find-011',
    severity: 'highly_suspicious',
    category: 'Encryption',
    title: 'VeraCrypt Encrypted Container Created on USB',
    description:
      'A 2 GB VeraCrypt encrypted container (AES-256 + Serpent cascade) was created on the Kingston USB drive. The container was created using VeraCrypt Portable, which leaves minimal forensic traces. This suggests intent to conceal stolen data.',
    evidence: 'Prefetch / Amcache / evt-032',
    timestamp: '2026-03-16T10:48:00.000Z',
    relatedArtifacts: ['evt-032', 'node-009', 'node-017'],
    confidence: 0.97,
    recommendation:
      'The encrypted container should be preserved for potential future decryption attempts. Check for VeraCrypt volume headers in RAM dumps. The use of cascade encryption suggests high technical sophistication.',
  },
  {
    id: 'find-012',
    severity: 'highly_suspicious',
    category: 'Execution',
    title: 'Unsigned Data Export Tool Executed from Temp',
    description:
      'An unsigned executable (data_export_tool.exe) was run from the user\'s temp directory. The tool was used to convert the employee database SQL dump to CSV format for exfiltration. The binary is not in the approved software inventory and has no valid digital signature.',
    evidence: 'Prefetch / Amcache / evt-029',
    timestamp: '2026-03-16T10:00:05.000Z',
    relatedArtifacts: ['evt-028', 'evt-029', 'node-008'],
    confidence: 0.97,
    recommendation:
      'Submit data_export_tool.exe for malware analysis. Check the system for any additional unsigned binaries. Implement application whitelisting to prevent future unauthorized software execution.',
  },
  {
    id: 'find-013',
    severity: 'suspicious',
    category: 'Reconnaissance',
    title: 'Suspicious Search Queries — Admin Bypass Techniques',
    description:
      'The user searched for "password reset admin panel bypass" on Google Chrome. This suggests interest in privilege escalation or unauthorized access techniques. Combined with other evidence, this indicates possible planning for further malicious activity.',
    evidence: 'Chrome History / evt-014',
    timestamp: '2026-03-15T09:45:00.000Z',
    relatedArtifacts: ['evt-003', 'evt-014'],
    confidence: 0.91,
    recommendation:
      'Document the search query. Check if any admin panels were accessed. Review account permission changes for the user. Consider this as corroborating evidence of malicious intent.',
  },
  {
    id: 'find-014',
    severity: 'suspicious',
    category: 'Financial',
    title: 'Searches for Anonymous Bitcoin Purchases',
    description:
      'The user searched for "bitcoin wallet anonymous purchase prepaid" on DuckDuckGo and subsequently visited localbitcoins.com. This suggests intent to establish an anonymous financial channel, possibly for selling stolen data or purchasing additional tools.',
    evidence: 'Chrome History / evt-038, evt-039',
    timestamp: '2026-03-16T14:35:00.000Z',
    relatedArtifacts: ['evt-038', 'evt-039'],
    confidence: 0.89,
    recommendation:
      'Document the cryptocurrency-related activity. Check for any Bitcoin wallet addresses in recovered artifacts. Coordinate with financial crimes investigators if applicable.',
  },
  {
    id: 'find-015',
    severity: 'suspicious',
    category: 'Registry',
    title: 'Multiple Registry Modifications for Concealment',
    description:
      'Three separate registry modifications were made to conceal evidence: (1) USB notification suppression via run key, (2) UserAssist count clearing to hide recently accessed files, and (3) USBSTOR driver disabling to prevent future logging. These show deliberate anti-forensics planning.',
    evidence: 'Registry Hives / evt-019, evt-034, evt-035',
    timestamp: '2026-03-15T10:42:15.000Z',
    relatedArtifacts: ['evt-019', 'evt-034', 'evt-035'],
    confidence: 0.92,
    recommendation:
      'Document all registry modifications with before/after values. Revert the USBSTOR driver change. Use registry transaction logs to establish the exact timeline of modifications.',
  },
];

// =============================================================================
// KEYWORD RESULTS (8 keywords)
// =============================================================================

const keywordResults: KeywordResult[] = [
  {
    keyword: 'password',
    matches: [
      { file: 'Chrome History (keyword_search_terms)', line: 1, context: 'Search query: "password reset admin panel bypass"', source: 'browser_data' },
      { file: 'Registry (HKLM\\Software\\AcmeCorp\\AppConfig)', line: 1, context: 'DbConnectionString contains: Password=********', source: 'registry_hive' },
      { file: 'Bash History', line: 42, context: 'mysql -u admin -pPASSWORD123 -h DB-PROD-01', source: 'log_file' },
      { file: 'puttygen.exe args', line: 1, context: 'Key passphrase: (empty — no password protection)', source: 'prefetch' },
    ],
    totalMatches: 4,
  },
  {
    keyword: 'admin',
    matches: [
      { file: 'Chrome History (keyword_search_terms)', line: 1, context: 'Search query: "password reset admin panel bypass"', source: 'browser_data' },
      { file: 'Security Event Log (4672)', line: 234, context: 'Special privileges assigned: SeDebugPrivilege (admin group membership)', source: 'log_file' },
      { file: 'Security Event Log (4624)', line: 89, context: 'Logon as admin@acmecorp.local from 10.0.15.101', source: 'log_file' },
    ],
    totalMatches: 3,
  },
  {
    keyword: 'bitcoin',
    matches: [
      { file: 'Chrome History (keyword_search_terms)', line: 1, context: 'Search query: "bitcoin wallet anonymous purchase prepaid"', source: 'browser_data' },
      { file: 'Chrome History (URL)', line: 1, context: 'Visited: https://localbitcoins.com/buy-bitcoins-online/cash-by-mail/', source: 'browser_data' },
    ],
    totalMatches: 2,
  },
  {
    keyword: '.onion',
    matches: [
      { file: 'Tor circuit analysis', line: 1, context: 'SNI or DNS-like pattern detected: darknetmarketxxxx.onion', source: 'network_capture' },
      { file: 'Chrome History (keyword_search_terms)', line: 2, context: 'Search query: "how to access .onion sites safely"', source: 'browser_data' },
    ],
    totalMatches: 2,
  },
  {
    keyword: 'confidential',
    matches: [
      { file: 'Shellbags', line: 1, context: 'Opened: \\\\FILESERVER\\Projects\\confidential_project_proposal.pdf', source: 'windows_artifact' },
      { file: 'Jump Lists', line: 3, context: 'Recent: confidential_project_proposal.pdf, confidential_financials.xlsx', source: 'windows_artifact' },
      { file: 'Email (OST)', line: 447, context: 'Subject: RE: Confidential — Q2 Revenue Forecast (attached)', source: 'log_file' },
    ],
    totalMatches: 3,
  },
  {
    keyword: 'secret',
    matches: [
      { file: 'Bash History', line: 88, context: 'export DB_SECRET="ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"', source: 'log_file' },
      { file: 'Git config', line: 1, context: 'credential.helper store — secrets may be cached in .git-credentials', source: 'filesystem' },
    ],
    totalMatches: 2,
  },
  {
    keyword: 'encrypt',
    matches: [
      { file: 'Prefetch', line: 1, context: 'VeraCryptPortable.exe executed with /c /q /v F:\\hidden_container.hc', source: 'prefetch' },
      { file: 'Prefetch', line: 2, context: 'sdelete64.exe — secure deletion (encryption-adjacent tool)', source: 'prefetch' },
      { file: 'Registry', line: 1, context: 'VeraCrypt volume: AES-256 + Serpent (cascade encryption)', source: 'registry_hive' },
    ],
    totalMatches: 3,
  },
  {
    keyword: 'ssh',
    matches: [
      { file: 'SSH Auth Log (dev-server-03)', line: 1023, context: 'Accepted publickey for deploy from 10.0.15.101 RSA SHA256:backup@acmecorp.com', source: 'log_file' },
      { file: 'Prefetch', line: 1, context: 'puttygen.exe — generated RSA-4096 key pair', source: 'prefetch' },
      { file: 'USN Journal', line: 1, context: 'Created: F:\\keys\\ssh_key_backup.ppk', source: 'filesystem' },
    ],
    totalMatches: 3,
  },
];

// =============================================================================
// GEOIP RESULTS (7 locations)
// =============================================================================

const geoIPResults: GeoIPResult[] = [
  {
    ip: '185.220.101.34',
    country: 'Germany',
    city: 'Berlin',
    latitude: 52.52,
    longitude: 13.405,
    isp: 'Tor Project Exit Node / Hetzner Online GmbH',
    timestamp: '2026-03-15T09:25:33.000Z',
  },
  {
    ip: '185.220.101.42',
    country: 'Germany',
    city: 'Falkenstein',
    latitude: 50.478,
    longitude: 12.366,
    isp: 'Tor Relay Node / Hetzner Online GmbH',
    timestamp: '2026-03-15T09:32:10.000Z',
  },
  {
    ip: '203.45.67.89',
    country: 'Russia',
    city: 'Moscow',
    latitude: 55.7558,
    longitude: 37.6173,
    isp: 'CloudVault LLC — Bulletproof Hosting',
    timestamp: '2026-03-16T10:20:00.000Z',
  },
  {
    ip: '10.0.15.42',
    country: 'United States',
    city: 'New York, NY (Internal)',
    latitude: 40.7128,
    longitude: -74.006,
    isp: 'ACME Corp Internal Network',
    timestamp: '2026-03-16T08:05:12.000Z',
  },
  {
    ip: '10.0.15.101',
    country: 'United States',
    city: 'New York, NY (Internal)',
    latitude: 40.7128,
    longitude: -74.006,
    isp: 'ACME Corp Internal Network — Primary workstation IP',
    timestamp: '2026-03-15T08:12:33.000Z',
  },
  {
    ip: '198.51.100.23',
    country: 'Netherlands',
    city: 'Amsterdam',
    latitude: 52.3676,
    longitude: 4.9041,
    isp: 'Leaseweb — Tor Exit Node',
    timestamp: '2026-03-15T10:15:44.000Z',
  },
  {
    ip: '91.219.236.174',
    country: 'Ukraine',
    city: 'Kyiv',
    latitude: 50.4501,
    longitude: 30.5234,
    isp: 'Tor Middle Relay — Datacenter',
    timestamp: '2026-03-16T10:25:00.000Z',
  },
];

// =============================================================================
// ACTIVITY HEATMAP (7 days × 24 hours = 168 entries)
// =============================================================================

function generateHeatmap(): ActivityHeatmap[] {
  const heatmap: ActivityHeatmap[] = [];
  // Base activity pattern: low at night, spike during work hours, secondary spike evening
  for (let day = 1; day <= 7; day++) {
    for (let hour = 0; hour < 24; hour++) {
      let count = 0;
      // Night: very low
      if (hour >= 0 && hour < 6) count = Math.floor(Math.random() * 2);
      // Early morning ramp
      else if (hour >= 6 && hour < 8) count = Math.floor(Math.random() * 3) + 1;
      // Morning work
      else if (hour >= 8 && hour < 12) count = Math.floor(Math.random() * 8) + 3;
      // Lunch dip
      else if (hour >= 12 && hour < 14) count = Math.floor(Math.random() * 4) + 1;
      // Afternoon work
      else if (hour >= 14 && hour < 17) count = Math.floor(Math.random() * 7) + 3;
      // Evening wind-down
      else if (hour >= 17 && hour < 20) count = Math.floor(Math.random() * 5) + 1;
      // Night
      else count = Math.floor(Math.random() * 2);

      // Day 1 (Monday): March 15 — very high activity (suspicion day)
      if (day === 1 && hour >= 8 && hour < 12) count += 8;
      if (day === 1 && hour >= 14 && hour < 16) count += 5;

      // Day 2 (Tuesday): March 16 — high activity
      if (day === 2 && hour >= 8 && hour < 12) count += 10;
      if (day === 2 && hour >= 14 && hour < 17) count += 6;

      // Day 3 (Wednesday): March 17 — early morning spike
      if (day === 3 && hour >= 7 && hour < 9) count += 7;

      // Day 4 (Thursday): March 18 — minimal (investigation day)
      if (day === 4) count = Math.max(count - 2, 0);

      // Weekend: minimal
      if (day >= 6) count = Math.floor(Math.random() * 2);

      heatmap.push({ hour, day, count });
    }
  }
  return heatmap;
}

const heatmap: ActivityHeatmap[] = generateHeatmap();

// =============================================================================
// CHAIN OF CUSTODY (7 entries)
// =============================================================================

const chainOfCustody: CustodyEntry[] = [
  {
    id: 'coc-001',
    evidenceId: 'evid-001',
    action: 'Evidence Collected',
    performedBy: 'Det. Marcus Rivera',
    timestamp: '2026-03-18T08:30:00.000Z',
    details: 'Workstation WS-JDOE-01 seized from cubicle B-217. Write-blocker (Tableau T35u) applied. Physical evidence bag sealed with tamper-evident tape.',
    hash: 'sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
  },
  {
    id: 'coc-002',
    evidenceId: 'evid-001',
    action: 'Disk Image Created',
    performedBy: 'Forensic Examiner Sarah Chen',
    timestamp: '2026-03-18T09:15:00.000Z',
    details: 'Forensic duplicate created using FTK Imager 4.7.3. Source hash verified against destination hash. Image format: E01 with 64KB block size.',
    hash: 'sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
  },
  {
    id: 'coc-003',
    evidenceId: 'evid-002',
    action: 'Registry Hive Extracted',
    performedBy: 'Forensic Examiner Sarah Chen',
    timestamp: '2026-03-18T09:20:00.000Z',
    details: 'NTUSER.DAT extracted from forensic image. Mounted using Registry Explorer for analysis. Last written timestamp confirmed as 2026-03-17T16:45:00Z.',
  },
  {
    id: 'coc-004',
    evidenceId: 'evid-003',
    action: 'Browser Artifacts Extracted',
    performedBy: 'Forensic Examiner Sarah Chen',
    timestamp: '2026-03-18T09:25:00.000Z',
    details: 'Chrome History, Cookies, and Cache extracted from user profile directory. SQLite database found to be partially deleted; 847 entries recovered from MFT slack space.',
  },
  {
    id: 'coc-005',
    evidenceId: 'evid-006',
    action: 'USB Device Collected',
    performedBy: 'Det. Marcus Rivera',
    timestamp: '2026-03-18T10:00:00.000Z',
    details: 'SANSA 64GB USB drive found in desk drawer of subject. Write-blocker applied. Device bagged and labeled with serial number USB-SN-789012.',
    hash: 'sha256:f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7',
  },
  {
    id: 'coc-006',
    evidenceId: 'evid-007',
    action: 'Network Capture Received',
    performedBy: 'Network Security Engineer James Park',
    timestamp: '2026-03-18T10:15:00.000Z',
    details: 'PCAP file provided by IT Security from SPAN port mirror on access switch port WS-JDOE-01. Captured period: 2026-03-15 00:00 UTC through 2026-03-17 23:59 UTC.',
  },
  {
    id: 'coc-007',
    evidenceId: 'evid-001',
    action: 'Evidence Transferred to Secure Storage',
    performedBy: 'Evidence Custodian Lisa Thompson',
    timestamp: '2026-03-18T18:00:00.000Z',
    details: 'All physical and digital evidence transferred to evidence locker #14 at ACME Corp Security Office. Evidence room temperature: 68°F. Access log updated.',
  },
];

// =============================================================================
// ANALYSIS STATS
// =============================================================================

const stats = {
  totalEvents: 47,
  suspiciousCount: 28,
  criticalCount: 15,
  timeRange: {
    start: '2026-03-15T08:12:33.000Z',
    end: '2026-03-17T08:25:00.000Z',
  },
  topCategories: [
    { category: 'file_opened', count: 6 },
    { category: 'file_executed', count: 7 },
    { category: 'file_deleted', count: 5 },
    { category: 'network_connection', count: 4 },
    { category: 'data_exfiltration', count: 2 },
    { category: 'registry_change', count: 4 },
    { category: 'usb_connected', count: 4 },
    { category: 'web_page_visited', count: 3 },
    { category: 'login_attempt', count: 3 },
    { category: 'service_start', count: 1 },
    { category: 'file_downloaded', count: 1 },
    { category: 'file_created', count: 3 },
    { category: 'search_query', count: 2 },
    { category: 'system_shutdown', count: 1 },
    { category: 'browser_opened', count: 1 },
    { category: 'process_created', count: 1 },
    { category: 'file_modified', count: 1 },
    { category: 'driver_loaded', count: 1 },
  ],
};

// =============================================================================
// EXPORTED FUNCTIONS
// =============================================================================

export function getSampleAnalysisResult(): AnalysisResult {
  return {
    caseId: 'case-001',
    caseInfo: getSampleCaseInfo(),
    evidence: getSampleEvidence(),
    custody: chainOfCustody,
    timeline: timelineEvents,
    rewindSequence,
    suspiciousFindings,
    correlations: correlationGraph,
    heatmap,
    keywordResults,
    geoIPResults,
    iocs: [],
    stats,
  };
}

export function getSampleReport(): ForensicReport {
  return {
    caseInfo: getSampleCaseInfo(),
    evidenceSummary: getSampleEvidence(),
    timeline: timelineEvents,
    keyFindings: suspiciousFindings,
    rewindSequence,
    correlations: correlationGraph,
    heatmap,
    keywordResults,
    geoIPResults,
    chainOfCustody,
    conclusion:
      'Forensic analysis of workstation WS-JDOE-01 belonging to employee John Doe reveals a coordinated insider threat campaign spanning March 15–17, 2026. ' +
      'The subject systematically accessed and exfiltrated confidential corporate data through multiple channels: USB mass storage devices (totaling ~4.1 GB), cloud storage uploads (~2.3 GB to an external IP associated with bulletproof hosting in Russia), and a Dropbox upload (~4.2 MB). ' +
      'The stolen data includes the confidential project proposal, employee salary database, full employee database SQL dump, and the complete proprietary source code repository (3,427 files, 1.8 GB). ' +
      'The subject employed multiple anti-forensics techniques including secure file deletion (sdelete64), browsing history cleaning (BleachBit, Chrome History deletion), UserAssist registry clearing, and shadow copy service disabling via an unsigned kernel driver. ' +
      'Tor network usage was confirmed with connections to known directory authorities and relay nodes, including access to a darknet marketplace. ' +
      'The subject also established a persistent SSH backdoor on DEV-SERVER-03 and redirected the application database connection string to an external server. ' +
      'Suspicious cryptocurrency-related searches suggest intent to establish anonymous financial channels. ' +
      'RECOMMENDATION: Immediate law enforcement referral is warranted given the volume, sophistication, and multi-channel nature of the data exfiltration.',
    generatedAt: new Date().toISOString(),
  };
}
